spring:
  banner:
    location: banner.txt
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: Qq1196726420!
    url: jdbc:mysql://localhost:3306/blog?ServerTimeZone=UTC-4&CharacterEncoding=utf-8&UseUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initalSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    filters: stat,wall,log4j
mybatis:
  type-aliases-package: com.sox.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml